"""ilustracao do passeio

Revision ID: 4d5523b3c2e3
Revises: d758e86b8bad
Create Date: 2026-09-28 14:21:18.811291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5523b3c2e3'
down_revision = 'd758e86b8bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passeio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ilustracao', sa.String(length=30), server_default='cinema', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passeio', schema=None) as batch_op:
        batch_op.drop_column('ilustracao')

    # ### end Alembic commands ###
