"""perfis e permissoes do painel

Revision ID: 6802f6d3f643
Revises: efba62287685
Create Date: 2026-09-28 15:49:30.194132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6802f6d3f643'
down_revision = 'efba62287685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supabase_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('perfil', sa.String(length=10), server_default='ADMIN', nullable=False))
        batch_op.add_column(sa.Column('permissoes', sa.String(length=200), server_default='', nullable=False))
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_usuario', schema=None) as batch_op:
        batch_op.drop_column('criado_em')
        batch_op.drop_column('permissoes')
        batch_op.drop_column('perfil')
        batch_op.drop_column('supabase_id')

    # ### end Alembic commands ###
