"""midia no banco

Revision ID: 9bfba8258bec
Revises: 4d5523b3c2e3
Create Date: 2026-09-28 15:30:21.771600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfba8258bec'
down_revision = '4d5523b3c2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('midia',
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('dados', sa.LargeBinary(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('nome', name=op.f('pk_midia'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('midia')
    # ### end Alembic commands ###
