"""dados completos da escola

Revision ID: ac8442cb4873
Revises: 6802f6d3f643
Create Date: 2026-09-28 16:08:48.007927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8442cb4873'
down_revision = '6802f6d3f643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escola', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inep', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('cnpj', sa.String(length=18), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('ramal', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('diretor', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('vice_diretor', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('modalidade', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('turno', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('qtd_salas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('logradouro', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('complemento', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('uf', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('maps_link', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_escola_inep'), ['inep'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escola', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_escola_inep'), type_='unique')
        batch_op.drop_column('ativo')
        batch_op.drop_column('maps_link')
        batch_op.drop_column('cep')
        batch_op.drop_column('uf')
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')
        batch_op.drop_column('complemento')
        batch_op.drop_column('numero')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('qtd_salas')
        batch_op.drop_column('turno')
        batch_op.drop_column('modalidade')
        batch_op.drop_column('vice_diretor')
        batch_op.drop_column('diretor')
        batch_op.drop_column('ramal')
        batch_op.drop_column('telefone')
        batch_op.drop_column('email')
        batch_op.drop_column('cnpj')
        batch_op.drop_column('inep')

    # ### end Alembic commands ###
