"""estrutura inicial

Revision ID: d3cfedaae076
Revises: 
Create Date: 2026-09-28 12:47:51.609069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cfedaae076'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('ator_tipo', sa.String(length=20), nullable=False),
    sa.Column('ator_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=40), nullable=False),
    sa.Column('alvo', sa.String(length=120), nullable=True),
    sa.Column('detalhes', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_data_hora'), ['data_hora'], unique=False)

    op.create_table('escola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escola')),
    sa.UniqueConstraint('codigo', name=op.f('uq_escola_codigo'))
    )
    op.create_table('passeio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('destino', sa.String(length=200), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora_saida', sa.Time(), nullable=False),
    sa.Column('hora_retorno', sa.Time(), nullable=False),
    sa.Column('local_saida', sa.String(length=200), nullable=False),
    sa.Column('transporte', sa.String(length=200), nullable=True),
    sa.Column('orientacoes', sa.Text(), nullable=True),
    sa.Column('data_limite', sa.DateTime(), nullable=False),
    sa.Column('permite_alteracao', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('texto_declaracao', sa.Text(), nullable=False),
    sa.Column('versao_texto', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passeio')),
    sa.UniqueConstraint('public_id', name=op.f('uq_passeio_public_id'))
    )
    op.create_table('protocolo_sequencia',
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('ultimo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ano', name=op.f('pk_protocolo_sequencia'))
    )
    op.create_table('responsavel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('cpf_hash', sa.String(length=64), nullable=False),
    sa.Column('cpf_final', sa.String(length=2), nullable=False),
    sa.Column('data_nascimento_hash', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responsavel')),
    sa.UniqueConstraint('public_id', name=op.f('uq_responsavel_public_id'))
    )
    with op.batch_alter_table('responsavel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responsavel_cpf_hash'), ['cpf_hash'], unique=True)

    op.create_table('tentativa_acesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tentativa_acesso'))
    )
    with op.batch_alter_table('tentativa_acesso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tentativa_acesso_chave'), ['chave'], unique=False)
        batch_op.create_index(batch_op.f('ix_tentativa_acesso_data_hora'), ['data_hora'], unique=False)

    op.create_table('admin_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('login', sa.String(length=60), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], name=op.f('fk_admin_usuario_escola_id_escola')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_usuario')),
    sa.UniqueConstraint('login', name=op.f('uq_admin_usuario_login'))
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('protocolo', sa.String(length=20), nullable=False),
    sa.Column('codigo_validacao', sa.String(length=14), nullable=False),
    sa.Column('passeio_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.Column('versao_texto', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.JSON(), nullable=False),
    sa.Column('arquivo', sa.String(length=200), nullable=True),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('data_geracao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['passeio_id'], ['passeio.id'], name=op.f('fk_documento_passeio_id_passeio')),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsavel.id'], name=op.f('fk_documento_responsavel_id_responsavel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documento')),
    sa.UniqueConstraint('protocolo', name=op.f('uq_documento_protocolo')),
    sa.UniqueConstraint('public_id', name=op.f('uq_documento_public_id'))
    )
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documento_codigo_validacao'), ['codigo_validacao'], unique=True)
        batch_op.create_index(batch_op.f('ix_documento_passeio_id'), ['passeio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documento_responsavel_id'), ['responsavel_id'], unique=False)

    op.create_table('turma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('ano', sa.String(length=40), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], name=op.f('fk_turma_escola_id_escola')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turma'))
    )
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turma_escola_id'), ['escola_id'], unique=False)

    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('matricula', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], name=op.f('fk_aluno_escola_id_escola')),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], name=op.f('fk_aluno_turma_id_turma')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aluno')),
    sa.UniqueConstraint('matricula', name=op.f('uq_aluno_matricula')),
    sa.UniqueConstraint('public_id', name=op.f('uq_aluno_public_id'))
    )
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aluno_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aluno_turma_id'), ['turma_id'], unique=False)

    op.create_table('passeio_turma',
    sa.Column('passeio_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['passeio_id'], ['passeio.id'], name=op.f('fk_passeio_turma_passeio_id_passeio')),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], name=op.f('fk_passeio_turma_turma_id_turma')),
    sa.PrimaryKeyConstraint('passeio_id', 'turma_id', name=op.f('pk_passeio_turma'))
    )
    op.create_table('autorizacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('passeio_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.String(length=20), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('versao_texto', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(length=30), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], name=op.f('fk_autorizacao_aluno_id_aluno')),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], name=op.f('fk_autorizacao_documento_id_documento')),
    sa.ForeignKeyConstraint(['passeio_id'], ['passeio.id'], name=op.f('fk_autorizacao_passeio_id_passeio')),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsavel.id'], name=op.f('fk_autorizacao_responsavel_id_responsavel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_autorizacao')),
    sa.UniqueConstraint('passeio_id', 'aluno_id', name='uq_autorizacao_passeio_aluno'),
    sa.UniqueConstraint('public_id', name=op.f('uq_autorizacao_public_id'))
    )
    with op.batch_alter_table('autorizacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autorizacao_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_autorizacao_passeio_id'), ['passeio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_autorizacao_responsavel_id'), ['responsavel_id'], unique=False)

    op.create_table('passeio_aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passeio_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], name=op.f('fk_passeio_aluno_aluno_id_aluno')),
    sa.ForeignKeyConstraint(['passeio_id'], ['passeio.id'], name=op.f('fk_passeio_aluno_passeio_id_passeio')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passeio_aluno')),
    sa.UniqueConstraint('passeio_id', 'aluno_id', name='uq_passeio_aluno_par')
    )
    with op.batch_alter_table('passeio_aluno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passeio_aluno_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_passeio_aluno_passeio_id'), ['passeio_id'], unique=False)

    op.create_table('responsavel_aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('tipo_vinculo', sa.String(length=30), nullable=False),
    sa.Column('responsavel_legal', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], name=op.f('fk_responsavel_aluno_aluno_id_aluno')),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsavel.id'], name=op.f('fk_responsavel_aluno_responsavel_id_responsavel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responsavel_aluno')),
    sa.UniqueConstraint('responsavel_id', 'aluno_id', name='uq_responsavel_aluno_par')
    )
    with op.batch_alter_table('responsavel_aluno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responsavel_aluno_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_responsavel_aluno_responsavel_id'), ['responsavel_id'], unique=False)

    op.create_table('autorizacao_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autorizacao_id', sa.Integer(), nullable=False),
    sa.Column('situacao_anterior', sa.String(length=20), nullable=True),
    sa.Column('situacao_nova', sa.String(length=20), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=300), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_usuario.id'], name=op.f('fk_autorizacao_historico_admin_id_admin_usuario')),
    sa.ForeignKeyConstraint(['autorizacao_id'], ['autorizacao.id'], name=op.f('fk_autorizacao_historico_autorizacao_id_autorizacao')),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], name=op.f('fk_autorizacao_historico_documento_id_documento')),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsavel.id'], name=op.f('fk_autorizacao_historico_responsavel_id_responsavel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_autorizacao_historico'))
    )
    with op.batch_alter_table('autorizacao_historico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autorizacao_historico_autorizacao_id'), ['autorizacao_id'], unique=False)

    op.create_table('documento_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('autorizacao_id', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['autorizacao_id'], ['autorizacao.id'], name=op.f('fk_documento_item_autorizacao_id_autorizacao')),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], name=op.f('fk_documento_item_documento_id_documento')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documento_item'))
    )
    with op.batch_alter_table('documento_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documento_item_autorizacao_id'), ['autorizacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documento_item_documento_id'), ['documento_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documento_item_documento_id'))
        batch_op.drop_index(batch_op.f('ix_documento_item_autorizacao_id'))

    op.drop_table('documento_item')
    with op.batch_alter_table('autorizacao_historico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autorizacao_historico_autorizacao_id'))

    op.drop_table('autorizacao_historico')
    with op.batch_alter_table('responsavel_aluno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responsavel_aluno_responsavel_id'))
        batch_op.drop_index(batch_op.f('ix_responsavel_aluno_aluno_id'))

    op.drop_table('responsavel_aluno')
    with op.batch_alter_table('passeio_aluno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passeio_aluno_passeio_id'))
        batch_op.drop_index(batch_op.f('ix_passeio_aluno_aluno_id'))

    op.drop_table('passeio_aluno')
    with op.batch_alter_table('autorizacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autorizacao_responsavel_id'))
        batch_op.drop_index(batch_op.f('ix_autorizacao_passeio_id'))
        batch_op.drop_index(batch_op.f('ix_autorizacao_aluno_id'))

    op.drop_table('autorizacao')
    op.drop_table('passeio_turma')
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aluno_turma_id'))
        batch_op.drop_index(batch_op.f('ix_aluno_escola_id'))

    op.drop_table('aluno')
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turma_escola_id'))

    op.drop_table('turma')
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documento_responsavel_id'))
        batch_op.drop_index(batch_op.f('ix_documento_passeio_id'))
        batch_op.drop_index(batch_op.f('ix_documento_codigo_validacao'))

    op.drop_table('documento')
    op.drop_table('admin_usuario')
    with op.batch_alter_table('tentativa_acesso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tentativa_acesso_data_hora'))
        batch_op.drop_index(batch_op.f('ix_tentativa_acesso_chave'))

    op.drop_table('tentativa_acesso')
    with op.batch_alter_table('responsavel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responsavel_cpf_hash'))

    op.drop_table('responsavel')
    op.drop_table('protocolo_sequencia')
    op.drop_table('passeio')
    op.drop_table('escola')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_data_hora'))
        batch_op.drop_index(batch_op.f('ix_audit_log_acao'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
