"""configuracoes, imagem e prazo de alteracao

Revision ID: d758e86b8bad
Revises: d3cfedaae076
Create Date: 2026-09-28 14:16:47.097896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd758e86b8bad'
down_revision = 'd3cfedaae076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao',
    sa.Column('chave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chave', name=op.f('pk_configuracao'))
    )
    with op.batch_alter_table('passeio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texto_termo', sa.Text(), server_default='Declaro que sou responsável legal pelo(s) aluno(s) selecionado(s) e confirmo esta autorização.', nullable=False))
        batch_op.add_column(sa.Column('prazo_alteracao_horas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('imagem', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passeio', schema=None) as batch_op:
        batch_op.drop_column('imagem')
        batch_op.drop_column('prazo_alteracao_horas')
        batch_op.drop_column('texto_termo')

    op.drop_table('configuracao')
    # ### end Alembic commands ###
