"""admin por email (supabase auth)

Revision ID: efba62287685
Revises: 1b0e7f733da3
Create Date: 2026-09-28 15:42:21.404070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efba62287685'
down_revision = '1b0e7f733da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=160), nullable=True))
        batch_op.alter_column('senha_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_admin_usuario_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_usuario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_admin_usuario_email'), type_='unique')
        batch_op.alter_column('senha_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
