"""dados importados de alunos e responsaveis

Revision ID: f7e85f89f1b6
Revises: ac8442cb4873
Create Date: 2026-09-28 16:36:39.032972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e85f89f1b6'
down_revision = 'ac8442cb4873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_externo', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('cpf_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('cpf_final', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('ano_letivo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('situacao_matricula', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_aluno_cpf_hash'), ['cpf_hash'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_aluno_id_externo'), ['id_externo'])

    with op.batch_alter_table('responsavel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_externo', sa.String(length=40), nullable=True))
        batch_op.alter_column('cpf_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('cpf_final',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_responsavel_id_externo'), ['id_externo'])

    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segmento', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.drop_column('segmento')

    with op.batch_alter_table('responsavel', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_responsavel_id_externo'), type_='unique')
        batch_op.alter_column('cpf_final',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('cpf_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('id_externo')

    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_aluno_id_externo'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_aluno_cpf_hash'))
        batch_op.drop_column('situacao_matricula')
        batch_op.drop_column('ano_letivo')
        batch_op.drop_column('cpf_final')
        batch_op.drop_column('cpf_hash')
        batch_op.drop_column('id_externo')

    # ### end Alembic commands ###
